version: "3.8"

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  proxy:
    container_name: proxy
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /volumes/proxy/certs:/etc/nginx/certs
      - /volumes/proxy/vhost:/etc/nginx/vhost.d
      - /volumes/proxy/html:/usr/share/nginx/html

  proxy-acme:
    container_name: proxy-acme
    image: nginxproxy/acme-companion
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /volumes/proxy-acme/acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
